[tox]
requires = tox >= 4
envlist = py313-mopidy3, py313-mopidy4, py314-mopidy4, lint

[testenv]
deps =
    pytest
    mopidy3: setuptools < 82
    mopidy3: Mopidy == 3.4.2
    mopidy3: PyGObject >= 3.50
    mopidy4: Mopidy == 4.0.1

commands =
    python -m pytest -q {posargs}

[testenv:lint]
skip_install = true
deps =
    ruff==0.15.22

commands = python -m ruff check mopiqtt tests setup.py
